### ISSUE TITLE
Acrescentar campo UN para os produtos

### ISSUE THREAD

**Issue by leonardo-silva** [ifnmgsal-inf/Prototipo-iFstorage#1]
É necessário saber a unidade (UN) para os produtos adquiridos e/ou utilizados, e.g., KG, GR, SC, etc

**Comment by italoCesarSilvaOliveira** [comment]
Tivemos uma conversa com o cliente sobre as unidades de medida dos produtos da nota de empenho. De acordo com a Katiussia, nossa cliente, as unidades de medida vão depender dos produtos que serão inclusos no sistema. Unidades como quilograma, grama, unidade terão no programa.
